# Zebrad configuration for testnet
[network]
network = "Testnet"
listen_addr = "0.0.0.0:18233"

[state]
cache_dir = "/var/lib/zebrad"
delete_old_database = false

[rpc]
listen_addr = "0.0.0.0:18232"
parallel_cpu_threads = 0

[tracing]
buffer_limit = 128000
